version: '3.3'
services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: '2CUATRIMESTRE'
      # Usuario no root
      MYSQL_USER: 'ivan'
      # Password para el usuario
      MYSQL_PASSWORD: 'toor'
      # Password para el root
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      # puerto expuesto : puerto del contenedor
      - '3306:3306'
    expose:
      # abre el puerto del contenedor
      - '3306'
      # Donde los datos seran persistentes
    volumes:
      - my-db:/var/lib/mysql
# Nombre del volumen
volumes:
  my-db:
